require:
  - rubocop-rspec

AllCops:
  NewCops: enable
  Exclude:
    - "Gemfile"
    - "Gemfile.lock"
    - "spec/spec_helper.rb"

Layout/LineLength:
  Max: 150

Style/FrozenStringLiteralComment:
  Enabled: false

Style/Documentation:
  Enabled: false

RSpec/ExampleLength:
  Max: 30

RSpec/MultipleExpectations:
  Max: 10
